/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.blacklocus.logback.s3.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum LogLevel { 
  TRACE, DEBUG, INFO, WARN, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LogLevel\",\"namespace\":\"com.blacklocus.logback.s3.avro\",\"symbols\":[\"TRACE\",\"DEBUG\",\"INFO\",\"WARN\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
